### ISSUE TITLE
Feedback: spec organisation and discovery

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#113]
As a newcomer to the Filecoin project, I'm bringing some fresh eyes and may be able to stand in for future implementers. In this issue I offer some suggestions for the specs repo as a whole, and I hope to file some future ones about specific specs. I recognise that these are still WIP and many imperfections are known to you already–apologies in advance if it's annoying for me to point them out again.

"I" below means "I as an external developer" with reasonable domain knowledge but little knowledge about specific tools, protocols, or algorithms used.

- [x] It would be much more helpful to host the gitbook output that refer to how to build it. I initially didn't bother, and suffered a substandard navigation experience since I didn't realise some filenames were magic. (→ #118)
- [x] The root README needs an index or table of contents to describe relationships between specs and a suggested reading order. I eventually found SUMMARY.md and INTRO.md which are good starts, but weren't obvious. They should be explicitly called out in README. (#117, ...)
- [ ] A much more detailed architecture description would be very helpful, with at least a few sentences about the logical protocols and their roles within the Filecoin system and relationship to each other. A diagram would help here. E.g. https://github.com/filecoin-project/go-filecoin/issues/1676 (#117)
- [x] The goal/s and non-goals of the specs as a collection should be stated up front. @whyrusleeping suggested to me that the eventual goal is sufficient detail to build an interoperable node from scratch. (#117)
- [ ] It's not clear what the specs are ideally specifying. Wire protocols? Consensus rules? Internal Go code APIs? Technical design for implementing some functionality (which might not belong here)? I expected wire protocols and consensus rules. It would be helpful to clearly identify the level of abstraction each spec is operating at. In the architecture diagram, explain which bits the specs should specify. The prevalence of Go code make the distinctions hard to see.
- [ ] As part of the introduction, a brief overview of the communication stack would be helpful, especially as I'm likely not familiar with the bits: CBOR, libp2p, .... This should answer basic questions, or point to answers, like "how are peers addressed and discovered", "what do messages look like", "how are messages transported". If the spec used `text/json` over HTTP then maybe this wouldn't be required, but otherwise needs to be stated. (#117, ...)
- [ ] After a top-down overview, I suggest arranging the specs in a *bottom-up* order, so that the building blocks are specified before they are used. So data structures, signatures, proofs etc come first, then application protocols, then consensus rules.
- [ ] For wire protocols, there might be a better DSL than Go code (especially if I don't know Go but am implementing a node in a different language). If there's a standard way of presenting CBOR schemas, use that. Else a pseudo-protobuf language could work? Perhaps C syntax if you must use code. For tables of constants, just use a table.
- [ ] Go interfaces like in [storage market](https://github.com/filecoin-project/specs/blob/master/storage-market.md) and discussion of "methods called" on "actors" seem out of place. I'm expecting a list of message formats and notes about where they can be sent and what semantics they bear.
- [ ] The following appear to be mostly tech design sketches, it's not clear what they're specifying: [sync](https://github.com/filecoin-project/specs/blob/master/sync.md), [mining](https://github.com/filecoin-project/specs/blob/master/mining.md).
- [ ] Long procedural code snippets contained there are bound to diverge from the actual code. I suggest a high-level pseudocode for illustrating typical exchanges.
- [ ] There's lots of "we should" and "we need" and other opinion and design discussion. In a spec, I expect only a crisp description of what is necessary to participate in the protocols.

Feel free to use or not use the checkboxes above to indicate processing of each item, even if your processing is deciding to take no action.
