### ISSUE TITLE
DesignDocs - Sprint 1

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/specs#29]
We are starting Sprint 1 of [the DesignDocs effort](https://docs.google.com/document/d/1v5XQvX23jF-OU6o6Q888kW0Rk1IskpGU01SqQ_rdd9c/edit).

- Start: 2018-09-06 (Thu)
- End: 2018-09-18 (Tue)

Focused on important requirements [for alpha](https://docs.google.com/document/d/1N6JPZckm3ji4FCo5HZjolK7U4G62FJrwT3aRRF3DUb8/edit?disco=AAAAB0EIzw4&ts=5b868f2e):
- [x] [Alpha DesignDoc](https://github.com/filecoin-project/pm/issues/52)
- [ ] Proofs
  - [ ] [Sector Base (was SSS)](https://github.com/filecoin-project/rust-proofs/issues/167)
  - [ ] [FPS](https://github.com/filecoin-project/rust-proofs/issues/174)
  - [ ] [ZigZag](https://github.com/filecoin-project/rust-proofs/issues/163)
  - [ ] [POsT research investigation](https://github.com/filecoin-project/rust-proofs/issues/158) Not a true design doc in this context, but linking here for visibility.
- [ ] [Mining protocol](https://github.com/filecoin-project/pm/issues/28)
- [ ] VM & message processing interface/designdoc
- [x] Filecoin Token Locking
- [ ] Address format
- [x] [Storage Power Consensus](https://github.com/filecoin-project/pm/issues/56)
- [ ] Networking Interfaces

Allocations are written in [the doc, for now](https://docs.google.com/document/d/1v5XQvX23jF-OU6o6Q888kW0Rk1IskpGU01SqQ_rdd9c/edit#). Will move to [the queue](https://docs.google.com/spreadsheets/d/1FsAw_JDSUhUASJdkWsxdu1wpcnnFY3NfcgpetfDEkkA/edit#gid=0).

(still playing around with best formats, forgive duplication)
