### ISSUE TITLE
Complete spec for sector sets and related datastructures

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs#298]
A lot of this work seems close to landing.  This issue calls out the need to get all of this great work written up in the spec and canonicalized to facilitate development storage protocol faults.

- [ ] [Sector Sets.](https://github.com/filecoin-project/specs/blob/master/data-structures.md#sectorset) These are currently unspecified.  However there is a lot of work [in this issue](https://github.com/filecoin-project/specs/issues/116) that looks close to landing.
- [ ]  **Sector IDs.** [In the above issue](https://github.com/filecoin-project/specs/issues/116) the discussion indicates that we can give the miner full selection over the sector ID.  This is in conflict with the current spec for [CommitSector](https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector).  We need to settle on a sector ID assignment scheme.
- [ ] [Bitfields](https://github.com/filecoin-project/specs/blob/master/data-structures.md#bitfield) are currently not speced (encoding still TBD).  However [this proposal](https://github.com/filecoin-project/specs/issues/133) looks accepted.  And the chosen rle+ encoding scheme is [referenced in the spec](https://github.com/filecoin-project/specs/blob/master/data-structures.md#rle-bitset-encoding).  We just need to close the loop and specify how bitfields are encoded.
- [ ] **Bitfield/FaultSet/SectorSet Operations**.  These show up frequently unspecified in SubmitPoSt.  This is discussed in enough detail [here](https://github.com/filecoin-project/specs/issues/119) that implementors can probably make progress with only a Bitfield and SectorSet spec.  For completeness implementers need to be able to write: 
  - `ValidateFaultSets([]FaultSet, Bitfield, Bitfield)`
  - `AggregateBitfileds([]FaultSet)`
  - `Subtract(Bitfield, Bitfield)`
  - `Filter(SectorSet, []FaultSet)`
  - `Sizeof(SectorSet)`
- [ ] [FaultSets](https://github.com/filecoin-project/specs/blob/master/data-structures.md#faultset).  These are mostly specified when a Bitfield spec is merged but the encoding still TBD implies there is a little work to do after this happens.  Also again looking at Why's comments [here](https://github.com/filecoin-project/specs/issues/119) it seems like there is still some uncertainty on how to timestamp faults.

**Comment by pooja** [comment]
cc @pooja @dignifiedquire

**Comment by laser** [comment]
@ZenGround0 

> In the above issue the discussion indicates that we can give the miner full selection over the sector ID. This is in conflict with the current spec for CommitSector. We need to settle on a sector ID assignment scheme.

FYI: The spec for `CommitSector` has recently changed to accommodate miners selecting sector IDs.

**Comment by whyrusleeping** [comment]
The bitfield operations in submit post should be clearer with #310

**Comment by pooja** [comment]
Let's review this PR: https://github.com/filecoin-project/specs/pull/333/
Also related is: https://github.com/filecoin-project/specs/issues/116

**Comment by mishmosh** [comment]
@ZenGround0 would you consider sector sets spec'd to your liking now? (if yes please close)
