### ISSUE TITLE
TODO for July 23

### ISSUE THREAD

**Issue by pooja** [filecoin-project/specs#378]
## @whyrusleeping:
- [ ] **Upgradeability**: Document the approach to upgrading the protocol, versioning, governance. Addresses #277, #197 
- [x] **Specify behavior of unspec'ed actor functions**: #273 
- [ ] **Improve the spec for deal arbitration**: #200, #89, #343, #353, #306
- [ ] **Make sure the IPLD HAMT specs land**: Follow these PRs https://github.com/ipld/specs/pull/109 and https://github.com/ipld/specs/pull/131, and close issue #224 when those are merged
- [x] **Review faults (from dig), PoSt (from dig) specs**

## @dignifiedquire:
- [ ] **Complete PoSt spec**: Spans many issues, including #371, #332, #321, #375, #119
- [ ] **Resolve faults open issues/questions**: Spans many issues, including #92, #292, #328 

## @nicola:
- [ ] **Finish Proofs PR**: Add bucket and DRG sampling to the proofs spec
- [ ] **PoSt spec**: Work with dig and 

## @pooja:
- [ ] **Write VerifyTipSet**: #369 
- [ ] **Complete signatures spec**: Rewrite signatures.md, review PR #210 
- [ ] **Add appendix**: Include #55, #65, architecture diagram, and API interface
- [ ] **Add diagram style notes**: #372

## @sternhenri:
- [x] #290
- [x] #176 
- [x] **Review https://github.com/filecoin-project/specs/pull/334/files**
- [x] https://github.com/filecoin-project/specs/pull/351
- [x] drive home https://github.com/filecoin-project/specs/pull/403

## @jesseclay:
- [x] **Initial FIL distribution**: #157

## To pick up next week (in addition to some from the existing backlog):
- **VM**: #226, #225, #176 (@dignifiedquire)
- **Spec'ing gas**: #79 
- **Upgrading proofs**: #132

**Comment by pooja** [comment]
We'll need to continue working on this this week, and hope to close out many of these issues next week.

**Comment by pooja** [comment]
Some of these issues are hairy beasts, e.g. faults/post, so continuing to plug away at those!

**Comment by pooja** [comment]
Replaced by #418
