### ISSUE TITLE
TODO for August 6

### ISSUE THREAD

**Issue by pooja** [filecoin-project/specs#418]
Closes out #378 

## @whyrusleeping:
- [ ] Review PR #383 (P0, slashing mechanism from zx)
- [ ] Review PR #395 (P0, PIP PR from porcu)
- [ ] Review PR #367 (and close #333 if we merge 367) 
- [ ] Review PR #326 (old PR that looks ready to merge)
- [ ] Review PR #324 (old PR that looks ready to merge)
- [ ] Review PR #416 (jesse's PR about unlocking mechanism)
- [ ] **Make sure the IPLD HAMT specs land:** Follow these PRs ipld/specs#109 and ipld/specs#131, and close issue #224 when those are merged
- [ ] **Upgradeability:** Document the approach to upgrading the protocol, versioning, governance. Addresses #277, #197

## @sternhenri:
- [ ] **Improve the spec for deal arbitration:** #200, #89, #343, #353, #306, also address signed deal responses, miner automated response to arbitration challenges (if any), handle terminated data transfer/flaky miners and clients

## @dignifiedquire:
- [ ] Review PR #412 
- [ ] **Complete PoSt spec #332 :** Spans many issues, including #371, #332, #321, #375, #119
- [ ] **Resolve faults open issues/questions in #379 :** Spans many issues, including #92, #292, #328 

## @nicola:
- [ ] **Finish Proofs PR:** Add bucket and DRG sampling to the proofs spec

## @laser:
- [ ] Finish up PR #318 

## @pooja:
- [ ] Write VerifyTipSet: #369
- [ ] Complete signatures spec: Rewrite signatures.md, review PR #210
- [ ] Add appendix: Include #55, #65, architecture diagram, and API interface
- [ ] Add diagram style notes: #372

## To pick up next week (in addition to some from the existing backlog):
- VM: #226, #225, #176 (@dignifiedquire)
- Spec'ing gas: #79
- Upgrading proofs: #132
