### ISSUE TITLE
🚀 Specs v1.0 Plan

### ISSUE THREAD

**Issue by bvohaska** [filecoin-project/specs#43]
## This is the master plan for getting `Specs` into version 1

Using this issue to track work that needs to be done in order for the 'spec' to be complete.

### Refine & Review Specs

- [ ] Approve/reject all PRs generated before Nov. 2018
- [ ] Seek developer approval for beta specs
- [ ] 🚀 Ensure Retrieval & Storage Market specs are accurate
- [x] 🚀 retrieval market completion - https://github.com/filecoin-project/go-filecoin/issues/1283
- [ ] 🚀 storage market completion - #130 
- [ ] 🚀 payment channels - usage
- [ ] 🚀 process on how to sync the blockchain
- [ ] 🚀 Add searchable wiki generated from specs (ex. GitBook)

### New Specs

- [ ] **IPLD Spec**
- [ ] **libp2p Spec**
- [ ] 🚀 **Faults Spec**
- [ ] 🚀 **Signature spec** - message signatures - #131 
- [ ] 🚀 **Proofs Spec** 
  - [x] Document interfaces
    - https://github.com/filecoin-project/specs/pull/133
  - [ ] Document specifics
- [ ] **Hello protocol** 
  - https://github.com/filecoin-project/go-filecoin/issues/1252
  - #153 
- [ ] **Message processing** (aka, how do i do state transitions?) - https://github.com/filecoin-project/go-filecoin/issues/1259
- [ ] **Local data storage**
  - Should document *what* is stored, not how its stored
  - https://github.com/filecoin-project/go-filecoin/issues/1311
- [ ] **Blockchain Sync** - https://github.com/filecoin-project/go-filecoin/issues/1318

### Documentation

- [ ] 🚀 **'How to use the spec'** document
  - [ ] Standardize a process for adding specs #113
  - [ ] Link to the spec process in the spec
- [ ] **'how to run a node'** should be documented
  - document started [here](https://github.com/filecoin-project/specs/blob/master/operation.md)
  - [ ] https://github.com/filecoin-project/go-filecoin/issues/1312
- [ ] **Serialization** - cbor CHAMP documentation
  - https://github.com/filecoin-project/go-filecoin/issues/1268
  - [ ] Link to 'cbor-ipld' spec - https://github.com/ipld/specs/pull/73
- [ ] **Account IDs** - How do account IDs work? - https://github.com/filecoin-project/go-filecoin/issues/1267

---
This plan uses the following issue as a template: https://github.com/filecoin-project/research/issues/26

**Legend**

- Required to ship: 🚀
- Effort (E):
  - **1**: the answer is known and requires simply document the answer in detail to count as 'solved'.
  - **2**: a solid day of work to get the solution fully thought out and written down.
  - **3**: anywhere from 2 to 4 days of dedicated research time to arrive at a solution to the problems
  - **4**: a solid week (possibly more) is needed to arrive at a solution. In person sync time with other researchers may be required for E4.
  - **5**: at least a week of research time is needed, very likely more, and that very little progress can be made without face to face discussion with others.

(@whyrusleeping)

**Comment by pooja** [comment]
I think we can close this since the work needed to launch the spec is being tracked in this repo's issues!
