### ISSUE TITLE
TODO for September 3

### ISSUE THREAD

**Issue by pooja** [filecoin-project/specs#460]
Closes out #418 

## @whyrusleeping:
- [ ] Review PR #367 (and close #333 if we merge 367) -- currently in-progress with some changes

## @sternhenri:
- [ ] #446
- [ ] #442 
- [ ] #457 
- [ ] **Improve the spec for deal arbitration:** #200, #89, #343, #353, #306, also address signed deal responses, miner automated response to arbitration challenges (if any), handle terminated data transfer/flaky miners and clients
- [ ] **Off-chain asks:** https://github.com/filecoin-project/specs/issues/309

--- ^ For this week

- [ ] **VDFs in EC**: https://github.com/filecoin-project/specs/issues/399
- [ ] **TipSet ordering in EC**: https://github.com/filecoin-project/specs/pull/453
- [x] **Tickets in SEAL**: https://github.com/filecoin-project/specs/issues/56
- [ ] **Validation**: https://github.com/filecoin-project/specs/issues/458

## @dignifiedquire:
- [ ] Review PR #412 
- [ ] Include slashing mechanism from #383
- [ ] **Complete PoSt spec #332 :** Spans many issues, including #371, #332, #321, #375, #119
- [ ] **Resolve faults open issues/questions in #379 :** Spans many issues, including #92, #292, #328 

## @nikkolasg:
- [ ] Review implementation of BLS sigs
- [ ] #441

## @laser:
- [ ] Finish up PR #318 

## @jbenet:
- [ ] Review issue https://github.com/filecoin-project/specs/issues/426

## @pooja:
- [ ] Write VerifyTipSet: #369
- [ ] Complete signatures spec: Rewrite signatures.md, review PR #210
- [ ] Add appendix: Include #55, #65, architecture diagram, and API interface
- [ ] Add diagram style notes: #372

## To pick up next week (in addition to some from the existing backlog):
- VM: #226, #225, #176 (@dignifiedquire)
- Spec'ing gas: #79
- Upgrading proofs: #132 
- **Upgradeability:** Document the approach to upgrading the protocol, versioning, governance. Addresses #277, #197
- **Make sure the IPLD HAMT specs land:** Follow these PRs ipld/specs#109 and ipld/specs#131, and close issue #224 when those are merged
- Others: #450 #445 #444 
- **Finish Proofs PR:** Add bucket and DRG sampling to the proofs spec
- Miner address updating: https://github.com/filecoin-project/specs/issues/415

**Comment by pooja** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TODO for September 3](https://trello.com/c/aTIvfb1Z/21-todo-for-september-3)
